<?php
/**
 * PinPointData
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PinPoint
 *
 * APC Overnight PinPoint Service. Locate parcel delivery information based on a consignment number and postcode.
 *
 * OpenAPI spec version: v1
 * Contact: developers@apc-overnight.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * PinPointData Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class PinPointData implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'PinPointData';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'delivery_depot' => 'int',
'delivery_depot_name' => 'string',
'delivery_depot_email' => 'string',
'delivery_depot_phone' => 'string',
'consignment_summary' => 'AllOfPinPointDataConsignmentSummary',
'item_journeys' => '\Swagger\Client\Model\ItemJourney[]',
'delivery_summary' => 'AllOfPinPointDataDeliverySummary',
'fmd' => 'AllOfPinPointDataFmd'    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'delivery_depot' => 'int32',
'delivery_depot_name' => null,
'delivery_depot_email' => null,
'delivery_depot_phone' => null,
'consignment_summary' => null,
'item_journeys' => null,
'delivery_summary' => null,
'fmd' => null    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'delivery_depot' => 'deliveryDepot',
'delivery_depot_name' => 'deliveryDepotName',
'delivery_depot_email' => 'deliveryDepotEmail',
'delivery_depot_phone' => 'deliveryDepotPhone',
'consignment_summary' => 'consignmentSummary',
'item_journeys' => 'itemJourneys',
'delivery_summary' => 'deliverySummary',
'fmd' => 'fmd'    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'delivery_depot' => 'setDeliveryDepot',
'delivery_depot_name' => 'setDeliveryDepotName',
'delivery_depot_email' => 'setDeliveryDepotEmail',
'delivery_depot_phone' => 'setDeliveryDepotPhone',
'consignment_summary' => 'setConsignmentSummary',
'item_journeys' => 'setItemJourneys',
'delivery_summary' => 'setDeliverySummary',
'fmd' => 'setFmd'    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'delivery_depot' => 'getDeliveryDepot',
'delivery_depot_name' => 'getDeliveryDepotName',
'delivery_depot_email' => 'getDeliveryDepotEmail',
'delivery_depot_phone' => 'getDeliveryDepotPhone',
'consignment_summary' => 'getConsignmentSummary',
'item_journeys' => 'getItemJourneys',
'delivery_summary' => 'getDeliverySummary',
'fmd' => 'getFmd'    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['delivery_depot'] = isset($data['delivery_depot']) ? $data['delivery_depot'] : null;
        $this->container['delivery_depot_name'] = isset($data['delivery_depot_name']) ? $data['delivery_depot_name'] : null;
        $this->container['delivery_depot_email'] = isset($data['delivery_depot_email']) ? $data['delivery_depot_email'] : null;
        $this->container['delivery_depot_phone'] = isset($data['delivery_depot_phone']) ? $data['delivery_depot_phone'] : null;
        $this->container['consignment_summary'] = isset($data['consignment_summary']) ? $data['consignment_summary'] : null;
        $this->container['item_journeys'] = isset($data['item_journeys']) ? $data['item_journeys'] : null;
        $this->container['delivery_summary'] = isset($data['delivery_summary']) ? $data['delivery_summary'] : null;
        $this->container['fmd'] = isset($data['fmd']) ? $data['fmd'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets delivery_depot
     *
     * @return int
     */
    public function getDeliveryDepot()
    {
        return $this->container['delivery_depot'];
    }

    /**
     * Sets delivery_depot
     *
     * @param int $delivery_depot delivery_depot
     *
     * @return $this
     */
    public function setDeliveryDepot($delivery_depot)
    {
        $this->container['delivery_depot'] = $delivery_depot;

        return $this;
    }

    /**
     * Gets delivery_depot_name
     *
     * @return string
     */
    public function getDeliveryDepotName()
    {
        return $this->container['delivery_depot_name'];
    }

    /**
     * Sets delivery_depot_name
     *
     * @param string $delivery_depot_name delivery_depot_name
     *
     * @return $this
     */
    public function setDeliveryDepotName($delivery_depot_name)
    {
        $this->container['delivery_depot_name'] = $delivery_depot_name;

        return $this;
    }

    /**
     * Gets delivery_depot_email
     *
     * @return string
     */
    public function getDeliveryDepotEmail()
    {
        return $this->container['delivery_depot_email'];
    }

    /**
     * Sets delivery_depot_email
     *
     * @param string $delivery_depot_email delivery_depot_email
     *
     * @return $this
     */
    public function setDeliveryDepotEmail($delivery_depot_email)
    {
        $this->container['delivery_depot_email'] = $delivery_depot_email;

        return $this;
    }

    /**
     * Gets delivery_depot_phone
     *
     * @return string
     */
    public function getDeliveryDepotPhone()
    {
        return $this->container['delivery_depot_phone'];
    }

    /**
     * Sets delivery_depot_phone
     *
     * @param string $delivery_depot_phone delivery_depot_phone
     *
     * @return $this
     */
    public function setDeliveryDepotPhone($delivery_depot_phone)
    {
        $this->container['delivery_depot_phone'] = $delivery_depot_phone;

        return $this;
    }

    /**
     * Gets consignment_summary
     *
     * @return AllOfPinPointDataConsignmentSummary
     */
    public function getConsignmentSummary()
    {
        return $this->container['consignment_summary'];
    }

    /**
     * Sets consignment_summary
     *
     * @param AllOfPinPointDataConsignmentSummary $consignment_summary consignment_summary
     *
     * @return $this
     */
    public function setConsignmentSummary($consignment_summary)
    {
        $this->container['consignment_summary'] = $consignment_summary;

        return $this;
    }

    /**
     * Gets item_journeys
     *
     * @return \Swagger\Client\Model\ItemJourney[]
     */
    public function getItemJourneys()
    {
        return $this->container['item_journeys'];
    }

    /**
     * Sets item_journeys
     *
     * @param \Swagger\Client\Model\ItemJourney[] $item_journeys item_journeys
     *
     * @return $this
     */
    public function setItemJourneys($item_journeys)
    {
        $this->container['item_journeys'] = $item_journeys;

        return $this;
    }

    /**
     * Gets delivery_summary
     *
     * @return AllOfPinPointDataDeliverySummary
     */
    public function getDeliverySummary()
    {
        return $this->container['delivery_summary'];
    }

    /**
     * Sets delivery_summary
     *
     * @param AllOfPinPointDataDeliverySummary $delivery_summary delivery_summary
     *
     * @return $this
     */
    public function setDeliverySummary($delivery_summary)
    {
        $this->container['delivery_summary'] = $delivery_summary;

        return $this;
    }

    /**
     * Gets fmd
     *
     * @return AllOfPinPointDataFmd
     */
    public function getFmd()
    {
        return $this->container['fmd'];
    }

    /**
     * Sets fmd
     *
     * @param AllOfPinPointDataFmd $fmd fmd
     *
     * @return $this
     */
    public function setFmd($fmd)
    {
        $this->container['fmd'] = $fmd;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
