<?php
/**
 * AllOfPinPointDataFmdTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PinPoint
 *
 * APC Overnight PinPoint Service. Locate parcel delivery information based on a consignment number and postcode.
 *
 * OpenAPI spec version: v1
 * Contact: developers@apc-overnight.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * AllOfPinPointDataFmdTest Class Doc Comment
 *
 * @category    Class
 * @description AllOfPinPointDataFmd
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class AllOfPinPointDataFmdTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "AllOfPinPointDataFmd"
     */
    public function testAllOfPinPointDataFmd()
    {
    }
}
