<?php
/**
 * ConsignmentSummaryTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PinPoint
 *
 * APC Overnight PinPoint Service. Locate parcel delivery information based on a consignment number and postcode.
 *
 * OpenAPI spec version: v1
 * Contact: developers@apc-overnight.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * ConsignmentSummaryTest Class Doc Comment
 *
 * @category    Class
 * @description Class providing the data for the Consignment Summary part of PinPoint
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ConsignmentSummaryTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ConsignmentSummary"
     */
    public function testConsignmentSummary()
    {
    }

    /**
     * Test attribute "consignment_number"
     */
    public function testPropertyConsignmentNumber()
    {
    }

    /**
     * Test attribute "dispatch_date"
     */
    public function testPropertyDispatchDate()
    {
    }

    /**
     * Test attribute "number_of_parcels"
     */
    public function testPropertyNumberOfParcels()
    {
    }

    /**
     * Test attribute "total_weight"
     */
    public function testPropertyTotalWeight()
    {
    }

    /**
     * Test attribute "service_code"
     */
    public function testPropertyServiceCode()
    {
    }

    /**
     * Test attribute "sender_reference"
     */
    public function testPropertySenderReference()
    {
    }
}
