<?php
/**
 * FollowMyDriverTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PinPoint
 *
 * APC Overnight PinPoint Service. Locate parcel delivery information based on a consignment number and postcode.
 *
 * OpenAPI spec version: v1
 * Contact: developers@apc-overnight.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * FollowMyDriverTest Class Doc Comment
 *
 * @category    Class
 * @description Follow My Driver Information class.
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class FollowMyDriverTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "FollowMyDriver"
     */
    public function testFollowMyDriver()
    {
    }

    /**
     * Test attribute "last_known_time_stamp"
     */
    public function testPropertyLastKnownTimeStamp()
    {
    }

    /**
     * Test attribute "driver_current_lat"
     */
    public function testPropertyDriverCurrentLat()
    {
    }

    /**
     * Test attribute "driver_current_long"
     */
    public function testPropertyDriverCurrentLong()
    {
    }

    /**
     * Test attribute "driver_current_stop"
     */
    public function testPropertyDriverCurrentStop()
    {
    }

    /**
     * Test attribute "delivery_stop"
     */
    public function testPropertyDeliveryStop()
    {
    }

    /**
     * Test attribute "delivery_point_lat"
     */
    public function testPropertyDeliveryPointLat()
    {
    }

    /**
     * Test attribute "delivery_point_long"
     */
    public function testPropertyDeliveryPointLong()
    {
    }

    /**
     * Test attribute "job_time_window_from"
     */
    public function testPropertyJobTimeWindowFrom()
    {
    }

    /**
     * Test attribute "job_time_window_to"
     */
    public function testPropertyJobTimeWindowTo()
    {
    }
}
