<?php
/**
 * TimeSpanTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * PinPoint
 *
 * APC Overnight PinPoint Service. Locate parcel delivery information based on a consignment number and postcode.
 *
 * OpenAPI spec version: v1
 * Contact: developers@apc-overnight.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.21
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

/**
 * TimeSpanTest Class Doc Comment
 *
 * @category    Class
 * @description TimeSpan
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class TimeSpanTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "TimeSpan"
     */
    public function testTimeSpan()
    {
    }

    /**
     * Test attribute "ticks"
     */
    public function testPropertyTicks()
    {
    }

    /**
     * Test attribute "days"
     */
    public function testPropertyDays()
    {
    }

    /**
     * Test attribute "hours"
     */
    public function testPropertyHours()
    {
    }

    /**
     * Test attribute "milliseconds"
     */
    public function testPropertyMilliseconds()
    {
    }

    /**
     * Test attribute "minutes"
     */
    public function testPropertyMinutes()
    {
    }

    /**
     * Test attribute "seconds"
     */
    public function testPropertySeconds()
    {
    }

    /**
     * Test attribute "total_days"
     */
    public function testPropertyTotalDays()
    {
    }

    /**
     * Test attribute "total_hours"
     */
    public function testPropertyTotalHours()
    {
    }

    /**
     * Test attribute "total_milliseconds"
     */
    public function testPropertyTotalMilliseconds()
    {
    }

    /**
     * Test attribute "total_minutes"
     */
    public function testPropertyTotalMinutes()
    {
    }

    /**
     * Test attribute "total_seconds"
     */
    public function testPropertyTotalSeconds()
    {
    }
}
